source 'https://rubygems.org'

ruby '2.0.0'

gem 'actionmailer', require: 'action_mailer'
gem 'dotenv'
gem 'github-markdown'
gem 'httparty'
gem 'letter_opener'
gem 'map'
gem 'omniauth-trello'
gem 'pg'
gem 'pry'
gem 'rake'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'thin'
